export default function menuTab() {
    
    //Clear content
    const content = document.getElementById('content');
    content.innerHTML = '';

    //Load header
    const div1 = document.createElement('div');
    const innerDiv1 = document.createElement('div');
    const header = document.createElement('h1');
    header.textContent = 'Menu';
    content.appendChild(div1);
    div1.appendChild(innerDiv1);
    innerDiv1.appendChild(header);

    //Load Entrees
    const div2 = document.createElement('div');
    div2.classList.add('container-outer');
    const innerDiv2 = document.createElement('div');
    innerDiv2.classList.add('container-inner','grid-container');
    const menuHead1 = document.createElement('h2');
    menuHead1.classList.add('grid-header');
    menuHead1.textContent = 'Entrees';
    const menuItem1 = document.createElement('h4');
    menuItem1.classList.add('item-name');
    menuItem1.textContent = 'Hamburger';
    const menuPrice1 = document.createElement('h4');
    menuPrice1.classList.add('item-listing');
    menuPrice1.textContent = '$7';
    const menuDesc1 = document.createElement('p');
    menuDesc1.classList.add('item-description');
    menuDesc1.textContent = 'Bun, Beef Patty, Ketchup, Lettuce, Onion, Tomato, Pickles';
    const menuItem2 = document.createElement('h4');
    menuItem2.classList.add('item-name');
    menuItem2.textContent = 'Cheeseburger';
    const menuPrice2 = document.createElement('h4');
    menuPrice2.classList.add('item-listing');
    menuPrice2.textContent = '$8';
    const menuDesc2 = document.createElement('p');
    menuDesc2.classList.add('item-description');
    menuDesc2.textContent = 'Bun, Beef Patty, Cheddar Cheese, Ketchup, Lettuce, Onion, Tomato, Pickles';
    const menuItem3 = document.createElement('h4');
    menuItem3.classList.add('item-name');
    menuItem3.textContent = 'Pizza';
    const menuPrice3 = document.createElement('h4');
    menuPrice3.classList.add('item-listing');
    menuPrice3.textContent = '$12';
    const menuDesc3 = document.createElement('p');
    menuDesc3.classList.add('item-description');
    menuDesc3.textContent = 'Dough, Pizza Sauce, Mozzarella Cheese, Choice of 2 toppings';
    const menuItem4 = document.createElement('h4');
    menuItem4.classList.add('item-name');
    menuItem4.textContent = 'Hotdog';
    const menuPrice4 = document.createElement('h4');
    menuPrice4.classList.add('item-listing');
    menuPrice4.textContent = '$4';
    const menuDesc4 = document.createElement('p');
    menuDesc4.classList.add('item-description');
    menuDesc4.textContent = 'Classic American Hotdog In A Bun';
    const menuItem5 = document.createElement('h4');
    menuItem5.classList.add('item-name');
    menuItem5.textContent = 'Corndog';
    const menuPrice5 = document.createElement('h4');
    menuPrice5.classList.add('item-listing');
    menuPrice5.textContent = '$5';
    const menuDesc5 = document.createElement('p');
    menuDesc5.classList.add('item-description');
    menuDesc5.textContent = 'Breaded Hotdog On A Stick';
    const menuItem6 = document.createElement('h4');
    menuItem6.classList.add('item-name');
    menuItem6.textContent = 'Mac & Cheese';
    const menuPrice6 = document.createElement('h4');
    menuPrice6.classList.add('item-listing');
    menuPrice6.textContent = '$6';
    const menuDesc6 = document.createElement('p');
    menuDesc6.classList.add('item-description');
    menuDesc6.textContent = 'Macaroni, Cheese, Sliced Hotdogs';
    content.appendChild(div2);
    div2.appendChild(innerDiv2);
    innerDiv2.appendChild(menuHead1);
    innerDiv2.appendChild(menuItem1);
    innerDiv2.appendChild(menuPrice1);
    innerDiv2.appendChild(menuDesc1);
    innerDiv2.appendChild(menuItem2);
    innerDiv2.appendChild(menuPrice2);
    innerDiv2.appendChild(menuDesc2);
    innerDiv2.appendChild(menuItem3);
    innerDiv2.appendChild(menuPrice3);
    innerDiv2.appendChild(menuDesc3);
    innerDiv2.appendChild(menuItem4);
    innerDiv2.appendChild(menuPrice4);
    innerDiv2.appendChild(menuDesc4);
    innerDiv2.appendChild(menuItem5);
    innerDiv2.appendChild(menuPrice5);
    innerDiv2.appendChild(menuDesc5);
    innerDiv2.appendChild(menuItem6);
    innerDiv2.appendChild(menuPrice6);
    innerDiv2.appendChild(menuDesc6);
    
    //Load Sides
    const div3 = document.createElement('div');
    div3.classList.add('container-outer');
    const innerDiv3 = document.createElement('div');
    innerDiv3.classList.add('container-inner','grid-container');
    const menuHead2 = document.createElement('h2');
    menuHead2.classList.add('grid-header');
    menuHead2.textContent = 'Sides';
    const menuItem7 = document.createElement('h4');
    menuItem7.classList.add('item-name');
    menuItem7.textContent = 'Fries';
    const menuPrice7 = document.createElement('h4');
    menuPrice7.classList.add('item-listing');
    menuPrice7.textContent = '$4';
    const menuDesc7 = document.createElement('p');
    menuDesc7.classList.add('item-description');
    menuDesc7.textContent = 'Crinkle Cut French Fries';
    const menuItem8 = document.createElement('h4');
    menuItem8.classList.add('item-name');
    menuItem8.textContent = 'Chips';
    const menuPrice8 = document.createElement('h4');
    menuPrice8.classList.add('item-listing');
    menuPrice8.textContent = '$2';
    const menuDesc8 = document.createElement('p');
    menuDesc8.classList.add('item-description');
    menuDesc8.textContent = 'Kettle Cooked --- Plain, Sour Cream, BBQ, Jalapeno';
    const menuItem9 = document.createElement('h4');
    menuItem9.classList.add('item-name');
    menuItem9.textContent = 'Tater Tots';
    const menuPrice9 = document.createElement('h4');
    menuPrice9.classList.add('item-listing');
    menuPrice9.textContent = '$4';
    const menuDesc9 = document.createElement('p');
    menuDesc9.classList.add('item-description');
    menuDesc9.textContent = 'Crispy Deep Fried Hashbrowns With Seasoning';
    const menuItem10 = document.createElement('h4');
    menuItem10.classList.add('item-name');
    menuItem10.textContent = 'Loaded Tater Tots';
    const menuPrice10 = document.createElement('h4');
    menuPrice10.classList.add('item-listing');
    menuPrice10.textContent = '$6';
    const menuDesc10 = document.createElement('p');
    menuDesc10.classList.add('item-description');
    menuDesc10.textContent = 'Tater Tots, Sour Cream, Chives, Bacon, Chicken';
    content.appendChild(div3);
    div3.appendChild(innerDiv3);
    innerDiv3.appendChild(menuHead2);
    innerDiv3.appendChild(menuItem7);
    innerDiv3.appendChild(menuPrice7);
    innerDiv3.appendChild(menuDesc7);
    innerDiv3.appendChild(menuItem8);
    innerDiv3.appendChild(menuPrice8);
    innerDiv3.appendChild(menuDesc8);
    innerDiv3.appendChild(menuItem9);
    innerDiv3.appendChild(menuPrice9);
    innerDiv3.appendChild(menuDesc9);
    innerDiv3.appendChild(menuItem10);
    innerDiv3.appendChild(menuPrice10);
    innerDiv3.appendChild(menuDesc10);
    
    //Load Drinks
    const div4 = document.createElement('div');
    div4.classList.add('container-outer');
    const innerDiv4 = document.createElement('div');
    innerDiv4.classList.add('container-inner','grid-container');
    const menuHead3 = document.createElement('h2');
    menuHead3.classList.add('grid-header');
    menuHead3.textContent = 'Beverages';
    const menuItem11 = document.createElement('h4');
    menuItem11.classList.add('item-name');
    menuItem11.textContent = 'Fountain Drink';
    const menuPrice11 = document.createElement('h4');
    menuPrice11.classList.add('item-listing');
    menuPrice11.textContent = '$2';
    const menuDesc11 = document.createElement('p');
    menuDesc11.classList.add('item-description');
    menuDesc11.textContent = 'Choice of Cola, Diet Cola, Root Beer, Orange, Grape';
    const menuItem12 = document.createElement('h4');
    menuItem12.classList.add('item-name');
    menuItem12.textContent = 'Milk';
    const menuPrice12 = document.createElement('h4');
    menuPrice12.classList.add('item-listing');
    menuPrice12.textContent = '$1';
    const menuDesc12 = document.createElement('p');
    menuDesc12.classList.add('item-description');
    menuDesc12.textContent = 'Choice of White, Chocolate, Strawberry';
    const menuItem13 = document.createElement('h4');
    menuItem13.classList.add('item-name');
    menuItem13.textContent = 'Coffee';
    const menuPrice13 = document.createElement('h4');
    menuPrice13.classList.add('item-listing');
    menuPrice13.textContent = '$1';
    const menuDesc13 = document.createElement('p');
    menuDesc13.classList.add('item-description');
    menuDesc13.textContent = 'Choice of Regular, Decaf';
    content.appendChild(div4);
    div4.appendChild(innerDiv4);
    innerDiv4.appendChild(menuHead3);
    innerDiv4.appendChild(menuItem11);
    innerDiv4.appendChild(menuPrice11);
    innerDiv4.appendChild(menuDesc11);
    innerDiv4.appendChild(menuItem12);
    innerDiv4.appendChild(menuPrice12);
    innerDiv4.appendChild(menuDesc12);
    innerDiv4.appendChild(menuItem13);
    innerDiv4.appendChild(menuPrice13);
    innerDiv4.appendChild(menuDesc13);

};